// Generated by https://quicktype.io
declare interface Comic_ShortBoxed {
    publisher: string
    description: string
    title: string
    price: string
    creators: string
    release_date: string
    diamond_id: string
}

declare interface Comic_ShortBoxed_SplitTitle {
    publisher: string
    issue_no: string
    description: string
    title: string
    price: string
    creators: string
    release_date: string
    diamond_id: string
}

declare interface Comic_ShortBoxed_SplitTitle_Image {
    publisher: string
    issue_no: string
    description: string
    title: string
    price: string
    creators: string
    release_date: string
    diamond_id: string
    image: string
}

// Generated by https://quicktype.io
declare interface Metron_ID_Res {
    count: number
    next: null
    previous: null
    results: Result[]
}

declare interface Result {
    id: number
    __str__: string
    cover_date: string
    modified: string
}

// Generated by https://quicktype.io
declare interface Metron_Comics {
    id: number
    publisher: Publisher
    series: Publisher
    volume: number
    number: string
    name: any[]
    cover_date: string
    store_date: string
    price: string
    sku: string
    upc: string
    page: null
    desc: string
    image: string
    arcs: any[]
    credits: Credit[]
    characters: Character[]
    teams: any[]
    variants: any[]
    modified: string
}

declare interface Character {
    id: number
    name: string
    modified: string
}

declare interface Credit {
    id: number
    creator: string
    role: Publisher[]
}

declare interface Publisher {
    id: number
    name: string
}
